/**
 * Sole-based grounding (spec 002 REQ-ANA-008 as amended by M3-00, issue #10):
 * `groundOffsetY = −jointMinY(A) + soleOffsetM(G) × height × feet`, joint-only at runtime.
 *
 * Fixtures: `fixture-ue5-22.json` (no `soleOffsetM`) and `fixture-ue5-22-sole.json` (the same rig
 * with `soleOffsetM: 0.02` on group `fixture-a`, `fixture-b` without a value), both generated by
 * `pnpm fixtures:build`. The spec's `g-a` / `g-b` are `fixture-a` / `fixture-b`.
 */
import {
  BufferAttribute,
  BufferGeometry,
  MeshBasicMaterial,
  Skeleton,
  SkinnedMesh,
  Vector3,
} from 'three';
import type {Bone} from 'three';
import {describe, expect, it} from 'vitest';
import {defaultAnatomy} from '@csg/parts-schema';
import type {AnatomyParams, RigDefinition} from '@csg/parts-schema';
import type {AnatomyBinding} from '../contracts/anatomy';
import type {BodySkeleton} from '../contracts/composition';
import {
  createTestRegistry,
  fixtureSpec,
} from '../composition/assembly-test-env';
import {createCharacterAssembly} from '../composition/character-assembly';
import {
  applyAnatomyToPose,
  computeGroundOffset,
  createAnatomyBinding,
  resetBodyToRest,
  soleOffsetOf,
} from './index';
import {createTestBody, loadFixtureRig} from './test-skeleton';

const plainRig = loadFixtureRig('fixture-ue5-22.json');
const soleRig = loadFixtureRig('fixture-ue5-22-sole.json');
const SOLE_M = 0.02;

function bind(rig: RigDefinition, group = 'fixture-a') {
  const body = createTestBody(rig, group);
  const res = createAnatomyBinding(rig, body);
  if (!res.ok) throw new Error(res.error.message);
  return {body, binding: res.value};
}

function params(over: Partial<AnatomyParams> = {}): AnatomyParams {
  return {...defaultAnatomy(), ...over};
}

function feetJointsMinY(body: BodySkeleton, binding: AnatomyBinding): number {
  let min = Infinity;
  const v = new Vector3();
  for (const name of binding.rig.anatomyBones.feet) {
    body.bones.get(name)?.traverse(o => {
      v.setFromMatrixPosition(o.matrixWorld);
      min = Math.min(min, v.y);
    });
  }
  return min;
}

/**
 * A feet mesh for AC-ANA-008.5, built in code: per foot two vertices, one at the foot joint's
 * rest position lowered by `SOLE_M` (the lowest rest vertex) and one 0.05 m above the joint,
 * each weighted 1.0 to its foot joint. Bound at the rest pose of the character skeleton.
 */
function feetMesh(body: BodySkeleton, binding: AnatomyBinding): SkinnedMesh {
  resetBodyToRest(binding);
  body.root.position.set(0, 0, 0);
  body.root.updateMatrixWorld(true);
  const feet = binding.rig.anatomyBones.feet.map(
    n => body.bones.get(n) as Bone,
  );
  const positions: number[] = [];
  const indices: number[] = [];
  const weights: number[] = [];
  const v = new Vector3();
  feet.forEach((bone, i) => {
    v.setFromMatrixPosition(bone.matrixWorld);
    for (const dy of [-SOLE_M, 0.05]) {
      positions.push(v.x, v.y + dy, v.z);
      indices.push(i, 0, 0, 0);
      weights.push(1, 0, 0, 0);
    }
  });
  const geometry = new BufferGeometry();
  geometry.setAttribute(
    'position',
    new BufferAttribute(new Float32Array(positions), 3),
  );
  geometry.setAttribute(
    'skinIndex',
    new BufferAttribute(new Uint16Array(indices), 4),
  );
  geometry.setAttribute(
    'skinWeight',
    new BufferAttribute(new Float32Array(weights), 4),
  );
  const mesh = new SkinnedMesh(geometry, new MeshBasicMaterial());
  body.root.add(mesh);
  body.root.updateMatrixWorld(true);
  mesh.bind(new Skeleton(feet));
  return mesh;
}

function lowestSkinnedY(mesh: SkinnedMesh): number {
  mesh.skeleton.update();
  const v = new Vector3();
  let min = Infinity;
  const count = mesh.geometry.getAttribute('position').count;
  for (let i = 0; i < count; i++) {
    mesh.getVertexPosition(i, v);
    v.applyMatrix4(mesh.matrixWorld);
    min = Math.min(min, v.y);
  }
  return min;
}

describe('REQ-ANA-008: sole-based ground offset (M3-00)', () => {
  it('REQ-ANA-021 rule f: the sole fixture carries soleOffsetM only on fixture-a', () => {
    expect(soleOffsetOf(bind(soleRig, 'fixture-a').binding)).toBe(SOLE_M);
    expect(soleOffsetOf(bind(soleRig, 'fixture-b').binding)).toBe(0);
    expect(soleOffsetOf(bind(plainRig, 'fixture-a').binding)).toBe(0);
  });

  it.each(['fixture-a', 'fixture-b'])(
    'AC-ANA-008.2: without soleOffsetM, legLength 0.7 and feet 1.5 put the lowest feet joint on y = 0 and the offset is negative (%s)',
    group => {
      const {body, binding} = bind(plainRig, group);
      const p = params({legLength: 0.7, feet: 1.5});
      const offset = computeGroundOffset(binding, p);
      resetBodyToRest(binding);
      applyAnatomyToPose(binding, p);
      body.root.position.y = offset;
      body.root.updateMatrixWorld(true);
      expect(Math.abs(feetJointsMinY(body, binding))).toBeLessThan(1e-3);
      expect(offset).toBeLessThan(0);
    },
  );

  it('AC-ANA-008.3: without soleOffsetM the default offset is exactly 0 (fixture-a rests its feet on y = 0) and repeated inputs are bit-identical', () => {
    expect(
      Object.is(computeGroundOffset(bind(plainRig).binding, params()), 0),
    ).toBe(true);
    for (const group of ['fixture-a', 'fixture-b']) {
      const p = params({legLength: 0.83, feet: 1.21, height: 1.07});
      expect(
        Object.is(
          computeGroundOffset(bind(plainRig, group).binding, p),
          computeGroundOffset(bind(plainRig, group).binding, {...p}),
        ),
      ).toBe(true);
    }
    // fixture-b of the sole variant has no value: joint-only, bit-identical to the plain rig.
    for (const p of [params(), params({legLength: 0.7, feet: 1.5})]) {
      expect(
        Object.is(
          computeGroundOffset(bind(soleRig, 'fixture-b').binding, p),
          computeGroundOffset(bind(plainRig, 'fixture-b').binding, p),
        ),
      ).toBe(true);
    }
  });

  it('AC-ANA-008.4: soleOffsetM 0.02 gives +0.02 at default anatomy and −jointMinY(A) + 0.036 at height 1.2, feet 1.5', () => {
    const {binding} = bind(soleRig);
    expect(
      Math.abs(computeGroundOffset(binding, params()) - 0.02),
    ).toBeLessThan(1e-9);
    const a = params({height: 1.2, feet: 1.5});
    // −jointMinY(A): the same anatomy on the rig without soleOffsetM (AC-ANA-008.2 term).
    const jointTerm = computeGroundOffset(bind(plainRig).binding, a);
    expect(
      Math.abs(computeGroundOffset(binding, a) - (jointTerm + 0.036)),
    ).toBeLessThan(1e-9);
  });

  it('AC-ANA-008.5: a g-a body whose feet vertices sit 0.02 m below the feet joints lands its lowest vertex on y = 0 at legLength 0.7, feet 1.5, height 0.8', () => {
    const {body, binding} = bind(soleRig);
    const mesh = feetMesh(body, binding);
    const p = params({legLength: 0.7, feet: 1.5, height: 0.8});
    const offset = computeGroundOffset(binding, p);
    resetBodyToRest(binding);
    applyAnatomyToPose(binding, p);
    body.root.position.y = offset;
    body.root.updateMatrixWorld(true);
    expect(Math.abs(lowestSkinnedY(mesh))).toBeLessThan(1e-4);
    // The joint-only offset would leave that sole 0.02 × 0.8 × 1.5 m under the ground.
    body.root.position.y = computeGroundOffset(bind(plainRig).binding, p);
    body.root.updateMatrixWorld(true);
    expect(lowestSkinnedY(mesh)).toBeCloseTo(-SOLE_M * 0.8 * 1.5, 6);
    mesh.geometry.dispose();
    (mesh.material as MeshBasicMaterial).dispose();
  });

  it('AC-ANA-008.7: the offset with every mesh loaded equals the skeleton-only one bit for bit and reads no vertex position', async () => {
    // The fixture character (body, shirt, sword) on the sole rig variant: the
    // assembly's binding has every mesh attached; the skeleton-only binding has none.
    const registry = createTestRegistry({rig: soleRig});
    const assembly = createCharacterAssembly({registry});
    expect((await assembly.setCharacter(fixtureSpec())).ok).toBe(true);
    const withMeshes = assembly.anatomy;
    if (withMeshes === null) throw new Error('no anatomy binding');
    expect(withMeshes.body.skeletonGroupId).toBe('fixture-a');
    expect(soleOffsetOf(withMeshes)).toBe(SOLE_M);

    // Spy: every position attribute of the character counts reads of its data.
    let reads = 0;
    assembly.root.traverse(o => {
      const geometry = (o as {geometry?: BufferGeometry}).geometry;
      const position = geometry?.getAttribute('position');
      if (position === undefined) return;
      const attr = position as BufferAttribute;
      const array = attr.array;
      Object.defineProperty(attr, 'array', {
        configurable: true,
        get() {
          reads++;
          return array;
        },
      });
      for (const m of ['getX', 'getY', 'getZ', 'getComponent'] as const) {
        const original = attr[m].bind(attr) as (...a: number[]) => number;
        (attr as unknown as Record<string, unknown>)[m] = (...a: number[]) => {
          reads++;
          return original(...a);
        };
      }
    });
    // Parameters never evaluated on this binding, so the offset is computed now.
    const p = params({legLength: 0.91, feet: 1.12, height: 1.03});
    const loaded = computeGroundOffset(withMeshes, p);
    expect(reads).toBe(0);
    const skeletonOnly = computeGroundOffset(
      bind(soleRig, withMeshes.body.skeletonGroupId).binding,
      {...p},
    );
    expect(Object.is(loaded, skeletonOnly)).toBe(true);
    assembly.dispose();
  });
});
