import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

import {describe, expect, it} from 'vitest';

import {renderShortcutsDoc, SHORTCUTS_DOC_PATH} from './shortcuts-doc';

describe('shortcuts doc generator', () => {
  it('AC-UX-021.1: generator output equals the committed keyboard shortcuts page', () => {
    const committed = readFileSync(
      fileURLToPath(new URL(`../../../${SHORTCUTS_DOC_PATH}`, import.meta.url)),
      'utf8',
    );
    expect(renderShortcutsDoc()).toBe(committed);
  });

  it('AC-UX-021.1: is deterministic and marks single-key bindings', () => {
    const text = renderShortcutsDoc();
    expect(renderShortcutsDoc()).toBe(text);
    expect(text).toContain('GENERATED by `pnpm docs:shortcuts`');
    expect(text).toMatch(/\| Randomize \| `R` \| `R` \| Single key \|/);
  });
});
