/**
 * Generated bundled-assets section of `ASSETS_LICENSE.md` (spec 011
 * REQ-AST-018). Pure: strings in, strings out.
 */

/** Marker that opens the generated section. */
export const SECTION_BEGIN =
  '<!-- assets:licenses:begin (generated by pnpm assets:licenses, do not edit by hand) -->';
/** Marker that closes the generated section. */
export const SECTION_END = '<!-- assets:licenses:end -->';

/** License record as stored in manifests. */
export interface LicenseInfo {
  license: string;
  author: string;
  sourceUrl: string;
  title?: string;
}

/** The slice of a manifest the generator needs. */
export interface LicensePack {
  packId: string;
  name: string;
  license: LicenseInfo;
  parts: ReadonlyArray<{id: string; license?: LicenseInfo}>;
  clips: ReadonlyArray<{id: string; license?: LicenseInfo}>;
}

/** Single-line, control-free text safe to put in Markdown. */
export function mdText(value: string): string {
  return (
    value
      // eslint-disable-next-line no-control-regex
      .replace(/[\u0000-\u001f\u007f]+/g, ' ')
      .replace(/[<>`]/g, '')
      .trim()
  );
}

function same(a: LicenseInfo, b: LicenseInfo): boolean {
  return (
    a.license === b.license &&
    a.author === b.author &&
    a.sourceUrl === b.sourceUrl
  );
}

/** Renders the generated section (markers included, no trailing newline). Deterministic. */
export function renderLicensesSection(packs: readonly LicensePack[]): string {
  const lines: string[] = [
    SECTION_BEGIN,
    '',
    '## Bundled 3D packs (generated)',
    '',
  ];
  lines.push(
    'Generated from `assets/packs/*/manifest.json` and `clips.json` by `pnpm assets:licenses`. Edit the pack config and rebuild instead of editing this section.',
    '',
  );
  const sorted = [...packs].sort((a, b) => a.packId.localeCompare(b.packId));
  if (sorted.length === 0) lines.push('No bundled packs are built yet.', '');
  for (const pack of sorted) {
    lines.push(`### ${mdText(pack.name)} (\`${mdText(pack.packId)}\`)`, '');
    lines.push(
      `- Author: ${mdText(pack.license.author)}`,
      `- License: ${mdText(pack.license.license)}`,
      `- Source: <${mdText(pack.license.sourceUrl)}>`,
      `- Contents: ${pack.parts.length} parts, ${pack.clips.length} clips`,
    );
    const overrides = [
      ...pack.parts.map(p => ({kind: 'part', ...p})),
      ...pack.clips.map(c => ({kind: 'clip', ...c})),
    ]
      .filter(e => e.license !== undefined && !same(e.license, pack.license))
      .sort((a, b) => `${a.kind}/${a.id}`.localeCompare(`${b.kind}/${b.id}`));
    for (const e of overrides) {
      const l = e.license as LicenseInfo;
      lines.push(
        `- Override, ${e.kind} \`${mdText(e.id)}\`: ${mdText(l.author)}, ${mdText(l.license)}, <${mdText(l.sourceUrl)}>`,
      );
    }
    lines.push('');
  }
  lines.push(SECTION_END);
  return lines.join('\n');
}

/**
 * Puts `section` into the document: replaces the marked block, or (no
 * markers) inserts it before `## Palettes` or at the end.
 */
export function applyLicensesSection(doc: string, section: string): string {
  const begin = doc.indexOf('<!-- assets:licenses:begin');
  const end = doc.indexOf(SECTION_END);
  if (begin >= 0 && end > begin) {
    return doc.slice(0, begin) + section + doc.slice(end + SECTION_END.length);
  }
  const anchor = doc.indexOf('\n## Palettes');
  if (anchor >= 0) {
    return `${doc.slice(0, anchor + 1)}${section}\n${doc.slice(anchor)}`;
  }
  return `${doc.replace(/\n*$/, '\n')}\n${section}\n`;
}

/** Line-set diff: `+` lines the generator wants, `-` lines the file has extra. */
export function diffLines(expected: string, actual: string): string[] {
  const e = expected.split('\n');
  const a = actual.split('\n');
  const aSet = new Set(a);
  const eSet = new Set(e);
  return [
    ...e.filter(l => l.trim() !== '' && !aSet.has(l)).map(l => `+ ${l}`),
    ...a.filter(l => l.trim() !== '' && !eSet.has(l)).map(l => `- ${l}`),
  ];
}

/** Extracts the marked block of a document, or null. */
export function extractLicensesSection(doc: string): string | null {
  const begin = doc.indexOf('<!-- assets:licenses:begin');
  const end = doc.indexOf(SECTION_END);
  if (begin < 0 || end <= begin) return null;
  return doc.slice(begin, end + SECTION_END.length);
}
